### ISSUE TITLE
The plugin doesn't work for ni versions below 0.15.0

### ISSUE THREAD

**Issue by willianba** [CanRau/asdf-ni#7]
**Describe the bug**

I have an app running with node v14 (we're fighting dependencies updates to upgrade it to v18)

I installed the plugin and found that ni v0.14 it's not using mjs files yet, so this is the version i have to use.

When I try to install v0.14 the plugins says that `Expected /Users/willianba/.asdf/installs/ni/0.14.0/ni to be executable.`

Same happened when i tried installing 0.13.0.

**Steps to reproduce**

`asdf install ni 0.14.0`

**Expected behavior**

The version should be installed without errors.

**Screenshots**

**Additional context**

**Comment by CanRau** [comment]
Hey @willianba sorry just now seeing this issue, just moved to a new place etc 🤓 

I actually switched from asdf to [mise](https://mise.jdx.dev/dev-tools/comparison-to-asdf.html) which works great for me as drop-in replacement and comes with npm and couple other backends along the asdf one so you can just install `ni` straight from npm via `mise use -g npm:@antfu/ni`

I'd understand if that's not interesting or an option for you, not sure that'd fix your node v14 issue 🤷🏼 

If I'm not mistaken right now, here's basically the line https://github.com/CanRau/asdf-ni/blob/47f458dd9873e7d6c76e2d23895f082dab8802fc/lib/utils.bash#L94 that renames the files which originally contain the `.mjs` extension and drops it, I put this plugin together rather quickly and am not the most familiar with bash, so there's probably cleaner ways for all of it 😅 
Anyway, can't spare time on this right now, you could add some lines which check if extension is using `.js` or whatever it was using before then run `mv "$f" "${f%.js}"` otherwise run the original line, and I could merge a PR, or you could clone the repo, replace the line as needed and use your local copy, think this should do it `asdf plugin add ni .` where `.` is the directory of the plugin

**Comment by willianba** [comment]
hey @CanRau!! thanks for the answer.
i never really liked asdf tbh 🤣 but i needed to version `ni` and this was the first thing i found. i'll try to make this work, and if i do, i'll open a PR.

thanks for the information. enjoy your new place!

**Comment by CanRau** [comment]
Thank you 🙏
Hope you make it work, maybe even using mise 💁🏻‍♂️

**Comment by willianba** [comment]
hey @CanRau
i gave mise a shot. still not my preferred tool, but it's working smoother than asdf. maybe i need time to get used to it, as it replaced my nvm too.

thanks for the recommendation. i will close this issue!!
